name: "Continuous Integration"

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
    tags:
    paths-ignore:
      - 'docs/**'

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
